Fix apport hook.
This fixes following crash:
NameError: global name 'attach_related_packages' is not defined

Closes: #702942
Thanks: Dmitry Shachnev <mitya57@gmail.com>
(cherry picked from commit 44f01d5eb109d021badbacf79d0acb4d3cfcdf79)

Signed-off-by: Edward Wang <edward.c.wang@compdigitec.com>